# CT30A5001 Network Programming
# Makefile for assignment 4.
#
# Made by:
#   Kimmo Pietiläinen
#
# Based on the makefile base file from course pages.

#---------- VARIABLES -----------------------------------------------------#
# Compiler to use
COMPILER=gcc

# Flags for compiler
CFLAGS=-Wall

# Flags for debugging, combine multiple flags with spaces (also variables)
DFLAGS=$(CFLAGS) -g

# Source files, separate multiple files with space, e.g. hello.c world.c
# List only .c -files, no headers
SOURCES1=yahtzeeclient.c
SOURCES2=yahtzeeserver.c

# Name of the output file
OUTPUT1=yahtzeeclient
OUTPUT2=yahtzeeserver


#--------- COMMANDS --------------------------------------------------------#

# Syntax: 
# <make command>:
# %tab%	<command>

# Build all
# "make"
all: build

# Build application
# "make build"
build:
	$(COMPILER) $(CFLAGS) $(SOURCES1) -o $(OUTPUT1)
	$(COMPILER) $(CFLAGS) $(SOURCES2) -o $(OUTPUT2)

# Build application with debugging information (use debug flags)
# "make debug"
#debug:
#	$(COMPILER) $(DFLAGS) $(SOURCES) -o $(OUTPUT)

# Remove generated files
# "make clean"
clean:
	rm $(OUTPUT1)
	rm $(OUTPUT2)

# Remove possible temp-files generated by editor (gedit)
# "make sanitize"
sanitize:
	rm *~

